### PR TITLE
Css canvas medical

### PR DESCRIPTION
**Pull request by Victor-Park**
Screen Shot 2022-03-21 at 8 57 16 AM
Screen Shot 2022-03-21 at 8 57 33 AM

Screen Shot 2022-03-21 at 8 57 25 AM

https://user-images.githubusercontent.com/99834589/159326137-f9e56cc1-919f-4594-9e8c-4da8f8162d8d.mov

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Victor! You seem to be missing the overlay on the hero image, please revise and submit a new screenshot with your revision.

**Comment by Victor-Park** [comment]
https://user-images.githubusercontent.com/99834589/159354169-7db1f237-cd37-47a7-b35d-5919b6c7a3b7.mov
Screen Shot 2022-03-21 at 12 58 59 PM
Screen Shot 2022-03-21 at 12 58 54 PM
Screen Shot 2022-03-21 at 12 58 47 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Victor! This is all great code and ready to be approved after you make one change: you have a lot of classes that are multiple words but no casing to differentiate where one word ends and the next begins. In CSS, the preferred case is `kebab-case`, where each word is separated by a hyphen. Please revise any classes you have that are multiple words without any delimiters, and add a hyphen to make it `kebab-case`.

**Comment by Victor-Park** [comment]
Made revisions to class names as advised. Not feeling too great about this challenge overall though (excessive use of padding/margin, frustration with flexbox alignment properties, etc). Is there anything else you'd point out that I should've done better given the tools we've learned so far?

**Review by codingcodymiller — APPROVED** [review]
Nice work, dude!! In answer to your question, the code you made for this is perfectly reasonable. This layout is very open with lots of empty space, so padding and margin will definitely play a part, but all of your uses of it were reasonable to accomplish the goal. There are ways to improve almost any code, but this is a very reasonable solution given your current level of knowledge 🤓

**Pull request merged**
